# Generated by Django 5.0.1 on 2024-05-01 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contenttable",
            fields=[
                (
                    "content_id",
                    models.IntegerField(
                        auto_created="true", primary_key="true", serialize=False
                    ),
                ),
                ("content_name", models.CharField(max_length=50)),
                ("content_img", models.ImageField(null=True, upload_to="")),
                ("content_desc", models.CharField(max_length=200)),
                ("content_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="registrationtable",
            fields=[
                ("name", models.CharField(max_length=30)),
                ("mobile_no", models.CharField(max_length=15)),
                (
                    "email",
                    models.CharField(
                        max_length=30, primary_key="true", serialize=False
                    ),
                ),
                ("district", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("user_type", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="crimetable",
            fields=[
                (
                    "case_id",
                    models.IntegerField(
                        auto_created="true", primary_key="true", serialize=False
                    ),
                ),
                ("victim_name", models.CharField(max_length=30)),
                ("victim_gender", models.CharField(max_length=50)),
                ("victim_age", models.CharField(max_length=15)),
                ("victim_dob", models.CharField(max_length=15)),
                ("mobile_no", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=40)),
                ("victim_address", models.CharField(max_length=50)),
                ("incident_type", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=25)),
                ("incident_date", models.CharField(max_length=20)),
                ("case_progress", models.IntegerField(default=0)),
                (
                    "userid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.registrationtable",
                    ),
                ),
            ],
        ),
    ]
