# Generated by Django 5.0.1 on 2024-05-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_contenttable_content_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocateCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("casestatus", models.IntegerField(default=0)),
                ("ManagerApproval", models.IntegerField(default=0)),
                ("AdminApproval", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=1000, null=True)),
                ("statisfied_Sts", models.IntegerField(default=0)),
                (
                    "case_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.crimetable",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.registrationtable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("findings", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                (
                    "case_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.crimetable",
                    ),
                ),
            ],
        ),
    ]
